### ISSUE TITLE
session()->invalidate() is enough !

### ISSUE THREAD

**Issue by alisalehi1380** [luisprmat/mini-blog#1]
![image](https://github.com/luisprmat/mini-blog/assets/111766206/4d23ed21-31c5-411b-8c69-470572efb20f)

hi my friend 👋

i think it is enough to use `session()->invalidate()` for delete all data in session (CSRF token too!).
you after than this ,you recreate CSRF token by `session()->regnerate` !

isn't that so?

**Comment by luisprmat** [comment]
[Laravel Breeze](https://github.com/laravel/breeze/blob/f7ae3e926f5259f8460cb7621be7ad2d436d9f83/stubs/default/app/Http/Controllers/Auth/AuthenticatedSessionController.php#L38) does it in this way. I trust in Laravel core developers!

**Comment by alisalehi1380** [comment]
tnk bro!
I did not know this. thank you I learned something new! 😀🙌
